import "./globals.css";
import "@/styles/styles.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "react-loading-skeleton/dist/skeleton.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/layout/Footer/Footer";
import Header from "./components/layout/Header";
import AuthProvider from "@/context/AuthContext";
import LoadingPage from "./components/loading-page";
import { Suspense } from "react";
import Providers from "@/redux/providers";
import { SkeletonTheme } from "react-loading-skeleton";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cua biển VN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthProvider>
            <SkeletonTheme baseColor={"#fff7f2"} highlightColor={"#FF8133"}>
              <Header />
              <Suspense fallback={<LoadingPage />}>{children}</Suspense>
              <Footer />
              <ToastContainer
                position="top-right"
                autoClose={4000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="colored"
              />
            </SkeletonTheme>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
